local M = {}

function M.get(c)
	return {
		-- Base
		Normal = { fg = c.fg, bg = c.bg },
		NormalFloat = { fg = c.fg, bg = c.bg_alt },
		NormalNC = { fg = c.fg, bg = c.bg },
		ColorColumn = { bg = c.bg_hl },
		Conceal = { fg = c.fg_muted },
		Cursor = { fg = c.bg, bg = c.cursor },
		CursorIM = { fg = c.bg, bg = c.cursor },
		CursorColumn = { bg = c.bg_hl },
		CursorLine = { bg = c.bg_hl },
		CursorLineNr = { fg = c.line_nr_hl, bold = true },
		Directory = { fg = c.blue },
		DiffAdd = { fg = c.git_add, bg = c.bg },
		DiffChange = { fg = c.git_change, bg = c.bg },
		DiffDelete = { fg = c.git_delete, bg = c.bg },
		DiffText = { fg = c.fg, bg = c.bg_sel },
		EndOfBuffer = { fg = c.bg_alt },
		ErrorMsg = { fg = c.error },
		VertSplit = { fg = c.border },
		WinSeparator = { fg = c.border },
		Folded = { fg = c.comment, bg = c.bg_alt },
		FoldColumn = { fg = c.comment, bg = c.bg },
		SignColumn = { fg = c.fg_muted, bg = c.bg },
		IncSearch = { fg = c.bg, bg = c.yellow, bold = true },
		Substitute = { fg = c.bg, bg = c.red },
		LineNr = { fg = c.line_nr },
		MatchParen = { fg = c.cyan, bold = true },
		ModeMsg = { fg = c.fg_bright, bold = true },
		MsgArea = { fg = c.fg },
		MoreMsg = { fg = c.green },
		NonText = { fg = c.fg_path },
		Pmenu = { fg = c.fg, bg = c.bg_alt },
		PmenuSel = { fg = c.fg_bright, bg = c.bg_sel, bold = true },
		PmenuSbar = { bg = c.bg_alt },
		PmenuThumb = { bg = c.fg_muted },
		Question = { fg = c.blue },
		QuickFixLine = { bg = c.bg_sel },
		Search = { fg = c.bg, bg = c.yellow },
		SpecialKey = { fg = c.fg_muted },
		SpellBad = { undercurl = true, sp = c.error },
		SpellCap = { undercurl = true, sp = c.warn },
		SpellLocal = { undercurl = true, sp = c.info },
		SpellRare = { undercurl = true, sp = c.hint },
		StatusLine = { fg = c.fg, bg = c.bg_alt },
		StatusLineNC = { fg = c.fg_muted, bg = c.bg_alt },
		TabLine = { fg = c.fg_muted, bg = c.bg_alt },
		TabLineFill = { bg = c.bg_dark },
		TabLineSel = { fg = c.fg_bright, bg = c.bg },
		Title = { fg = c.blue, bold = true },
		Visual = { bg = c.bg_sel },
		VisualNOS = { bg = c.bg_sel },
		WarningMsg = { fg = c.warn },
		Whitespace = { fg = c.indent },
		WildMenu = { fg = c.bg, bg = c.blue },
		WinBar = { fg = c.fg, bg = c.bg_alt },
		WinBarNC = { fg = c.fg_muted, bg = c.bg_alt },

		-- Syntax
		Comment = { fg = c.comment, italic = true },
		Constant = { fg = c.constant },
		String = { fg = c.string },
		Character = { fg = c.string },
		Number = { fg = c.number },
		Float = { fg = c.number },
		Boolean = { fg = c.constant },
		Identifier = { fg = c.fg_dim },
		Function = { fg = c.func },
		Statement = { fg = c.keyword, bold = true },
		Conditional = { fg = c.keyword, bold = true },
		Repeat = { fg = c.keyword, bold = true },
		Label = { fg = c.label },
		Operator = { fg = c.operator },
		Keyword = { fg = c.keyword, bold = true },
		Exception = { fg = c.red },
		PreProc = { fg = c.builtin },
		Include = { fg = c.builtin },
		Define = { fg = c.builtin },
		Macro = { fg = c.builtin },
		PreCondit = { fg = c.builtin },
		Type = { fg = c.type },
		StorageClass = { fg = c.keyword, bold = true },
		Structure = { fg = c.type },
		Typedef = { fg = c.type },
		Special = { fg = c.cyan },
		SpecialChar = { fg = c.cyan },
		Tag = { fg = c.cyan },
		Delimiter = { fg = c.fg_muted },
		SpecialComment = { fg = c.comment, bold = true },
		Debug = { fg = c.orange },
		Underlined = { underline = true },
		Ignore = { fg = c.fg_muted },
		Error = { fg = c.error },
		Todo = { fg = c.bg, bg = c.yellow, bold = true },

		-- Treesitter
		["@comment"] = { link = "Comment" },
		["@comment.documentation"] = { fg = c.comment, italic = true },
		["@error"] = { fg = c.error },
		["@none"] = { fg = c.fg },
		["@preproc"] = { link = "PreProc" },
		["@define"] = { link = "Define" },
		["@operator"] = { fg = c.operator },
		["@punctuation.delimiter"] = { fg = c.fg_muted },
		["@punctuation.bracket"] = { fg = c.fg_muted },
		["@punctuation.special"] = { fg = c.cyan },
		["@string"] = { link = "String" },
		["@string.regex"] = { fg = c.cyan },
		["@string.escape"] = { fg = c.cyan },
		["@string.special"] = { fg = c.cyan },
		["@character"] = { link = "Character" },
		["@character.special"] = { fg = c.cyan },
		["@boolean"] = { link = "Boolean" },
		["@number"] = { link = "Number" },
		["@float"] = { link = "Float" },
		["@function"] = { fg = c.func },
		["@function.builtin"] = { fg = c.builtin },
		["@function.call"] = { fg = c.func },
		["@function.macro"] = { fg = c.builtin },
		["@function.method"] = { fg = c.func },
		["@function.method.call"] = { fg = c.func },
		["@constructor"] = { fg = c.type },
		["@parameter"] = { fg = c.param },
		["@keyword"] = { fg = c.keyword, bold = true },
		["@keyword.function"] = { fg = c.keyword, bold = true },
		["@keyword.operator"] = { fg = c.keyword },
		["@keyword.return"] = { fg = c.keyword, bold = true },
		["@keyword.import"] = { fg = c.builtin },
		["@keyword.modifier"] = { fg = c.keyword, bold = true },
		["@keyword.repeat"] = { fg = c.keyword, bold = true },
		["@keyword.conditional"] = { fg = c.keyword, bold = true },
		["@keyword.exception"] = { fg = c.red },
		["@conditional"] = { link = "Conditional" },
		["@repeat"] = { link = "Repeat" },
		["@label"] = { fg = c.label },
		["@include"] = { link = "Include" },
		["@exception"] = { fg = c.red },
		["@type"] = { fg = c.type },
		["@type.builtin"] = { fg = c.builtin, bold = true },
		["@type.definition"] = { fg = c.type },
		["@type.qualifier"] = { fg = c.keyword },
		["@storageclass"] = { link = "StorageClass" },
		["@attribute"] = { fg = c.builtin },
		["@field"] = { fg = c.field },
		["@property"] = { fg = c.field },
		["@variable"] = { fg = c.variable },
		["@variable.builtin"] = { fg = c.builtin },
		["@variable.parameter"] = { fg = c.param },
		["@variable.member"] = { fg = c.field },
		["@constant"] = { fg = c.constant },
		["@constant.builtin"] = { fg = c.builtin, bold = true },
		["@constant.macro"] = { fg = c.builtin },
		["@namespace"] = { fg = c.blue },
		["@module"] = { fg = c.blue },
		["@symbol"] = { fg = c.cyan },
		["@text"] = { fg = c.fg },
		["@text.strong"] = { bold = true },
		["@text.emphasis"] = { italic = true },
		["@text.underline"] = { underline = true },
		["@text.strike"] = { strikethrough = true },
		["@text.title"] = { fg = c.blue, bold = true },
		["@text.literal"] = { fg = c.string },
		["@text.uri"] = { fg = c.cyan, underline = true },
		["@text.math"] = { fg = c.cyan },
		["@text.reference"] = { fg = c.blue },
		["@text.todo"] = { link = "Todo" },
		["@text.note"] = { fg = c.info, bold = true },
		["@text.warning"] = { fg = c.warn, bold = true },
		["@text.danger"] = { fg = c.error, bold = true },
		["@text.diff.add"] = { fg = c.git_add },
		["@text.diff.delete"] = { fg = c.git_delete },
		["@tag"] = { fg = c.red },
		["@tag.attribute"] = { fg = c.field },
		["@tag.delimiter"] = { fg = c.fg_muted },

		-- LSP semantic tokens
		["@lsp.type.class"] = { fg = c.type },
		["@lsp.type.comment"] = { link = "Comment" },
		["@lsp.type.decorator"] = { fg = c.builtin },
		["@lsp.type.enum"] = { fg = c.type },
		["@lsp.type.enumMember"] = { fg = c.constant },
		["@lsp.type.function"] = { fg = c.func },
		["@lsp.type.interface"] = { fg = c.interface, italic = true },
		["@lsp.type.keyword"] = { fg = c.keyword, bold = true },
		["@lsp.type.macro"] = { fg = c.builtin },
		["@lsp.type.method"] = { fg = c.func },
		["@lsp.type.modifier"] = { fg = c.keyword },
		["@lsp.type.namespace"] = { fg = c.blue },
		["@lsp.type.number"] = { fg = c.number },
		["@lsp.type.operator"] = { fg = c.operator },
		["@lsp.type.parameter"] = { fg = c.param },
		["@lsp.type.property"] = { fg = c.field },
		["@lsp.type.string"] = { fg = c.string },
		["@lsp.type.struct"] = { fg = c.type },
		["@lsp.type.type"] = { fg = c.type },
		["@lsp.type.typeParameter"] = { fg = c.param },
		["@lsp.type.variable"] = { fg = c.variable },
		["@lsp.mod.deprecated"] = { strikethrough = true },
		["@lsp.mod.readonly"] = { fg = c.constant },
		["@lsp.mod.static"] = { italic = true },

		-- Diagnostics
		DiagnosticError = { fg = c.error },
		DiagnosticWarn = { fg = c.warn },
		DiagnosticInfo = { fg = c.info },
		DiagnosticHint = { fg = c.hint },
		DiagnosticUnnecessary = { fg = c.comment },
		DiagnosticVirtualTextError = { fg = c.error, bg = c.bg_alt },
		DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.bg_alt },
		DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_alt },
		DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_alt },
		DiagnosticUnderlineError = { undercurl = true, sp = c.error },
		DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
		DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
		DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },

		-- LSP references
		LspReferenceText = { bg = c.bg_sel },
		LspReferenceRead = { bg = c.bg_sel },
		LspReferenceWrite = { bg = c.bg_sel },
		LspSignatureActiveParameter = { fg = c.param, bold = true },
		LspInlayHint = { fg = c.fg_muted, bg = c.bg_alt, italic = true },

		-- Gitsigns
		GitSignsAdd = { fg = c.git_add },
		GitSignsChange = { fg = c.git_change },
		GitSignsDelete = { fg = c.git_delete },
		GitSignsAddNr = { fg = c.git_add },
		GitSignsChangeNr = { fg = c.git_change },
		GitSignsDeleteNr = { fg = c.git_delete },
		GitSignsAddLn = { bg = c.bg_hl },
		GitSignsChangeLn = { bg = c.bg_hl },

		-- Telescope
		TelescopeNormal = { fg = c.fg, bg = c.bg_alt },
		TelescopeBorder = { fg = c.border, bg = c.bg_alt },
		TelescopePromptNormal = { fg = c.fg_bright, bg = c.bg_alt },
		TelescopePromptBorder = { fg = c.border, bg = c.bg_alt },
		TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
		TelescopePreviewTitle = { fg = c.bg, bg = c.green, bold = true },
		TelescopeResultsTitle = { fg = c.fg_muted, bg = c.bg_alt },
		TelescopeSelection = { fg = c.fg_bright, bg = c.bg_sel },
		TelescopeSelectionCaret = { fg = c.pink, bg = c.bg_sel },
		TelescopeMatching = { fg = c.yellow, bold = true },
		TelescopePromptPrefix = { fg = c.pink },

		-- nvim-cmp
		CmpItemAbbr = { fg = c.fg },
		CmpItemAbbrDeprecated = { fg = c.fg_muted, strikethrough = true },
		CmpItemAbbrMatch = { fg = c.yellow, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = c.yellow },
		CmpItemMenu = { fg = c.fg_muted, italic = true },
		CmpItemKindText = { fg = c.fg },
		CmpItemKindMethod = { fg = c.func },
		CmpItemKindFunction = { fg = c.func },
		CmpItemKindConstructor = { fg = c.type },
		CmpItemKindField = { fg = c.field },
		CmpItemKindVariable = { fg = c.variable },
		CmpItemKindClass = { fg = c.type },
		CmpItemKindInterface = { fg = c.interface },
		CmpItemKindModule = { fg = c.blue },
		CmpItemKindProperty = { fg = c.field },
		CmpItemKindUnit = { fg = c.number },
		CmpItemKindValue = { fg = c.constant },
		CmpItemKindEnum = { fg = c.type },
		CmpItemKindKeyword = { fg = c.keyword },
		CmpItemKindSnippet = { fg = c.cyan },
		CmpItemKindColor = { fg = c.pink },
		CmpItemKindFile = { fg = c.blue },
		CmpItemKindReference = { fg = c.field },
		CmpItemKindFolder = { fg = c.blue },
		CmpItemKindEnumMember = { fg = c.constant },
		CmpItemKindConstant = { fg = c.constant },
		CmpItemKindStruct = { fg = c.type },
		CmpItemKindEvent = { fg = c.orange },
		CmpItemKindOperator = { fg = c.operator },
		CmpItemKindTypeParameter = { fg = c.param },

		-- nvim-tree
		NvimTreeNormal = { fg = c.fg, bg = c.bg_alt },
		NvimTreeNormalNC = { fg = c.fg, bg = c.bg_alt },
		NvimTreeRootFolder = { fg = c.blue, bold = true },
		NvimTreeGitDirty = { fg = c.git_change },
		NvimTreeGitNew = { fg = c.git_add },
		NvimTreeGitDeleted = { fg = c.git_delete },
		NvimTreeSpecialFile = { fg = c.pink },
		NvimTreeIndentMarker = { fg = c.indent },
		NvimTreeImageFile = { fg = c.purple },
		NvimTreeSymlink = { fg = c.cyan },
		NvimTreeFolderName = { fg = c.blue },
		NvimTreeOpenedFolderName = { fg = c.blue, bold = true },
		NvimTreeEmptyFolderName = { fg = c.fg_muted },
		NvimTreeFolderIcon = { fg = c.blue },
		NvimTreeFileIcon = { fg = c.fg },
		NvimTreeWinSeparator = { fg = c.border, bg = c.bg_alt },

		-- which-key
		WhichKey = { fg = c.pink },
		WhichKeyGroup = { fg = c.blue },
		WhichKeyDesc = { fg = c.fg },
		WhichKeySeparator = { fg = c.fg_muted },
		WhichKeyFloat = { bg = c.bg_alt },
		WhichKeyValue = { fg = c.fg_muted },

		-- indent-blankline
		IblIndent = { fg = c.indent },
		IblScope = { fg = c.fg_muted },

		-- mini.indentscope
		MiniIndentscopeSymbol = { fg = c.fg_muted },

		-- Neogit / fugitive
		NeogitBranch = { fg = c.purple },
		NeogitRemote = { fg = c.pink },
		NeogitHunkHeader = { fg = c.fg, bg = c.bg_alt },
		NeogitHunkHeaderHighlight = { fg = c.blue, bg = c.bg_sel },
		NeogitDiffContextHighlight = { bg = c.bg_hl },
		NeogitDiffDeleteHighlight = { fg = c.git_delete },
		NeogitDiffAddHighlight = { fg = c.git_add },

		-- Dashboard / alpha
		DashboardHeader = { fg = c.blue },
		DashboardFooter = { fg = c.fg_muted, italic = true },
		DashboardShortCut = { fg = c.cyan },
		DashboardDesc = { fg = c.fg },
		DashboardKey = { fg = c.pink },

		-- Notify
		NotifyERRORBorder = { fg = c.error },
		NotifyWARNBorder = { fg = c.warn },
		NotifyINFOBorder = { fg = c.info },
		NotifyDEBUGBorder = { fg = c.fg_muted },
		NotifyTRACEBorder = { fg = c.purple },
		NotifyERRORIcon = { fg = c.error },
		NotifyWARNIcon = { fg = c.warn },
		NotifyINFOIcon = { fg = c.info },
		NotifyDEBUGIcon = { fg = c.fg_muted },
		NotifyTRACEIcon = { fg = c.purple },
		NotifyERRORTitle = { fg = c.error, bold = true },
		NotifyWARNTitle = { fg = c.warn, bold = true },
		NotifyINFOTitle = { fg = c.info, bold = true },
		NotifyDEBUGTitle = { fg = c.fg_muted, bold = true },
		NotifyTRACETitle = { fg = c.purple, bold = true },
		NotifyERRORBody = { fg = c.fg },
		NotifyWARNBody = { fg = c.fg },
		NotifyINFOBody = { fg = c.fg },
		NotifyDEBUGBody = { fg = c.fg },
		NotifyTRACEBody = { fg = c.fg },

		-- Lualine (handled by lualine theme, but fallbacks)
		StatusLineTerm = { fg = c.fg, bg = c.bg_alt },
		StatusLineTermNC = { fg = c.fg_muted, bg = c.bg_alt },

		-- Flash
		FlashBackdrop = { fg = c.fg_muted },
		FlashMatch = { fg = c.yellow, bg = c.bg_sel },
		FlashCurrent = { fg = c.bg, bg = c.yellow, bold = true },
		FlashLabel = { fg = c.bg, bg = c.pink, bold = true },

		-- Trouble
		TroubleText = { fg = c.fg },
		TroubleCount = { fg = c.purple, bg = c.bg_alt },
		TroubleNormal = { fg = c.fg, bg = c.bg_alt },

		-- Snacks
		SnacksPickerDir = { fg = c.fg_path },
	}
end

return M
